using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Warlander.Deedplanner.Editor.RegistryBrowser
{
    [InitializeOnLoad]
    internal static class RegistryBrowserGitHookInstaller
    {
        private const string HookContent =
            "#!/bin/sh\n" +
            "# Auto-generated by DeedPlanner Registry Browser. Do not edit manually.\n" +
            "if [ -n \"$(find Packages/Embeds -mindepth 1 -maxdepth 1 2>/dev/null)\" ]; then\n" +
            "  echo \"ERROR: Packages/Embeds/ contains embedded packages.\"\n" +
            "  echo \"Use the Registry Browser (Window > DeedPlanner > Registry Browser) to un-embed packages before committing.\"\n" +
            "  exit 1\n" +
            "fi\n" +
            "if grep -q '\"file:Embeds/' Packages/manifest.json 2>/dev/null; then\n" +
            "  echo \"ERROR: Packages/manifest.json still references embedded packages (file:Embeds/...).\"\n" +
            "  echo \"Use the Registry Browser (Window > DeedPlanner > Registry Browser) to un-embed packages before committing.\"\n" +
            "  exit 1\n" +
            "fi\n" +
            "exit 0\n";

        static RegistryBrowserGitHookInstaller()
        {
            EditorApplication.update += RunOnNextUpdate;
        }

        private static void RunOnNextUpdate()
        {
            EditorApplication.update -= RunOnNextUpdate;
            InstallHook();
        }

        private static void InstallHook()
        {
            try
            {
                string projectRoot = GitEmbedOperations.GetProjectRoot();
                string hooksDir = Path.Combine(projectRoot, ".git", "hooks");
                string hookPath = Path.Combine(hooksDir, "pre-commit");

                if (!Directory.Exists(hooksDir))
                    Directory.CreateDirectory(hooksDir);

                if (File.Exists(hookPath) && File.ReadAllText(hookPath) == HookContent)
                    return;

                File.WriteAllText(hookPath, HookContent, new UTF8Encoding(false));

                if (Environment.OSVersion.Platform != PlatformID.Win32NT)
                    MakeExecutable(hookPath);

                Debug.Log("[RegistryBrowser] Installed pre-commit hook to block commits with embedded packages.");
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[RegistryBrowser] Failed to install pre-commit hook: {ex.Message}");
            }
        }

        private static void MakeExecutable(string path)
        {
            try
            {
                var psi = new System.Diagnostics.ProcessStartInfo("chmod", $"+x \"{path}\"")
                {
                    UseShellExecute = false,
                    CreateNoWindow = true,
                };
                using System.Diagnostics.Process proc = System.Diagnostics.Process.Start(psi);
                proc?.WaitForExit();
            }
            catch
            {
                // chmod failure is non-fatal
            }
        }
    }
}
